# Generated by Django 2.2.6 on 2020-06-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='latlon',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='continent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='lat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='lon',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
