# Generated by Django 2.2.6 on 2020-06-30 00:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gymdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdetails',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to='gym_photos'), blank=True, null=True, size=None),
        ),
    ]
