# Generated by Django 3.0.4 on 2020-07-07 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gymdetails_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymdetails',
            name='photos',
        ),
    ]
